-- Include all needed lua file here to init neovim
require('plugins.bootstrap')
require('plugins.nvim-airline')
require('plugins.nvim-treesitter')
require('plugins.nvim-lsp')
require('plugins.nvim-autopair')
require('plugins.nvim-telescope')
require('plugins.nvim-indent')
require('plugins.nvim-dap')
require('configs.keybindings')
require('configs.options')
require('configs.colorscheme')
require('configs.autocmd')
