local call = require 'utils.pcallx'
call.load_module 'ftplugins.bootstrap'
call.load_module 'ftplugins.nvim-airline'
call.load_module 'ftplugins.nvim-autopairs'
call.load_module 'ftplugins.nvim-colors'
call.load_module 'ftplugins.nvim-mason'
call.load_module 'ftplugins.nvim-cmp'
call.load_module 'ftplugins.nvim-indent'
call.load_module 'ftplugins.nvim-telescope'
call.load_module 'ftplugins.nvim-dap'
