local lsp = require 'lsp.conf'
lsp.setup 'lua_ls'
lsp.setup 'gopls'
lsp.setup 'clangd'
lsp.setup 'jsonls'
lsp.setup 'yamlls'
lsp.setup 'marksman'
lsp.setup 'vimls'
lsp.setup 'bashls'
lsp.setup 'dockerls'
lsp.setup 'docker_compose_language_service'
